#+title: Linkmusario's NixOS Dotfiles
#+begin_quote
⚠ *WARNING:* These dotfiles are only meant to be used by me, and have only been tested by me.
#+end_quote
* Installation
Ensure you have flakes enabled by puttings this into your configuration.nix:
#+begin_src nix
{
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
}
#+end_src

Clone this repository:
#+begin_src sh
git clone https://github.com/linkmusario/olympix ~/olympix
#+end_src

Replace the hardware-configuration.nix in this folder with the one generated from the NixOS install:
#+begin_src sh
rm ~/olympix/hardware-configuration.nix
cp /etc/nixos/hardware-configuration.nix ~/olympix/hardware-configuration.nix
#+end_src

Finally, rebuild the system:
#+begin_src sh
sudo nixos-rebuild switch --flake ~/olympix#olympus
#+end_src

* Things That Might Need Changing
** 1. Username
These dotfiles use the "linkmusario" username. Either ensure the username already in the system is "linkmusario" or change the username found in =configuration.nix= to whatever the username on the system is.

** 2. Doom Config Location
   Doom Emacs has been installed imperatively, as it is a pain to install declaratively with NixOS (I'm dumb it's not actually that hard). Simply go to [[https://github.com/doomemacs/core][Doom Emacs]] and follow install instructions. The doom directory is symlinked to =~/.config/doom=, however, doom can sometimes look at the =~/.doom.d_= folder for the config files. Change the symlink locations accordingly in home.nix.

** 3. Kanata Device
   In the Kanata configuration (located in =configuration.nix=), the devices that Kanata observes are listed in =services.kanata.keyboards.internalKeyboard.devices=. If the keyboard being used is not a Ducky One 2 Mini then this setting will need to be changed. To look at the devices currently connected, run:
   #+begin_src sh
   ls /dev/input/by-id/ | rg "event-kbd"
   #+end_src
   Copy whatever the correct keyboard is replace the Ducky One 2 Mini. Ensure to keep the =/dev/input/by-id/= filepath in the setting.

* Reason For Name
Olympus has been hostname for Linux (beyond just NixOS) because of Kratos and the God of War games. My entire OS has various references to various interests of mine. However, mainly the references are to games because their the easiest references to make. Olympus is simply one of many references. The reason for why this repo is names olympix is because it is law that all NixOS dotfiles have 'ix' in it somewhere.

Regarding my username (Linkmusario), it is a mashup of Link, Samus, and Mario. Each character is linked (no pun intended) with a core memory and so have been mashed together to make this monstrosity of a name.
