#+title: Linkmusario's NixOS Dotfiles
#+begin_warning
Disclaimer: These dotfiles are only meant to be used by me, and have only been tested by me.
#+end_warning
* Installation
Ensure you have flakes enabled by puttings this into your configuration.nix:
#+begin_src nix
{
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
}
#+end_src

Clone this repository:
#+begin_src sh
git clone https://github.com/linkmusario/olympix ~/olympix
#+end_src

Replace the hardware-configuration.nix in this folder with the one generated from the NixOS install:
#+begin_src sh
rm ~/olympix/hardware-configuration.nix
cp /etc/nixos/hardware-configuration.nix ~/olympix/hardware-configuration.nix
#+end_src

Finally, rebuild the system:
#+begin_src sh
sudo nixos-rebuild switch --flake ~/olympix#olympus
#+end_src

#+begin_quote
Note: Doom Emacs has been installed imperatively, as it is a pain to install declaratively with NixOS (I'm dumb it's not actually that hard). Simply go to [[https://github.com/doomemacs/core][Doom Emacs]] and follow install instructions. The doom directory is symlinked to _~/.config/doom_, however, doom can sometimes look at the _~/.doom.d_ folder for the config files. Change the symlink locations accordingly in home.nix.
#+end_quote

* Reason For Name
Olympus has been hostname for Linux (beyond just NixOS) because of Kratos and the God of War games. My entire OS has various references to various interests of mine. However, mainly the references are to games because their the easiest references to make. Olympus is simply one of many references. The reason for why this repo is names olympix is because it is law that all NixOS dotfiles have 'ix' in it somewhere.

Regarding my username (Linkmusario), it is a mashup of Link, Samus, and Mario. Each character is linked (no pun intended) with a core memory and so have been mashed together to make this monstrosity of a name.
